#!/usr/bin/env python3
"""
Run integration-e2e inside the shadow network simulator. This can be helpful
vs running it directly for several reasons.

* shadow simulates time, and can collapse idle time. This speeds up the
  network bootstrapping step in particular.
* shadow tries to be deterministic. There are some gaps, but in general
  there *should* be less nondeterministic flakiness under shadow
  than when running natively.
"""

import atexit
import argparse
import chutney.shadow
import chutney.network_tests.verify
import ipaddress
import json
import shadowtools.config as scfg
import shadowtools.shadow_exec as shadow_exec
import os
import pathlib
import subprocess
import sys

from pathlib import Path
from chutney import TorNet
from typing import Final

import common
from config import Config

assert __name__ == "__main__", "Can't determine _SCRIPT_DIR"
_SCRIPT_DIR = Path(sys.argv[0]).parent.resolve()

def _configure_and_run_shadow(args: argparse.Namespace) -> None:
    toplevel = pathlib.Path(
        os.fsdecode(
            subprocess.check_output("git rev-parse --show-toplevel", shell=True)
        ).strip()
    )
    os.chdir(toplevel)

    # configure this test
    subprocess.check_call([_SCRIPT_DIR.joinpath("setup")])

    config = Config.load_json(Path(_SCRIPT_DIR).joinpath("arti.run.json"))
    config.export_env()

    # initialize the network
    subprocess.check_call(
        [_SCRIPT_DIR.joinpath("init")],
    )

    # Load the network we just initialized
    network = TorNet.Network.from_data_dir()

    ip_network: ipaddress.IPv4Network = ipaddress.IPv4Network("192.168.0.0/24")
    host_ips = iter(ip_network.hosts())
    controller_ip = next(host_ips)
    #XXX need this?
    test_domain_ip = next(host_ips)
    starting_ip = next(host_ips)
    network = chutney.shadow.rewrite_network_for_shadow_multihost(
        network,
        ip_network=ip_network,
        controller_ip=controller_ip,
        starting_ip=starting_ip,
    )

    # Init the *new* network, creating a new nodes directory as usual.
    # In principle it might be nice to support overwriting the
    # previous nodes directory in-place, to avoid creating an "extra" one
    # when the previous was generated specifically for this purpose, but
    # would probably open the door to subtle bugs and footguns.
    network.init(data_dir=Path(config.chutney_data_dir))

    controller_hostname = "controller-host"
    network_graph = chutney.shadow.generate_shadow_network_graph(
        network,
        controller_ip=controller_ip,
        controller_hostname=controller_hostname,
        node_latency="1 ms",
        node_bandwidth="1 Gbit",
        node_packet_loss=0.0,
    )
    shadow_config = chutney.shadow.generate_shadow_config(
        network,
        controller_hostname=controller_hostname,
        controller_ip=controller_ip,
        controller_args=chutney.shadow.wrap_cmd_in_running_network([
            'env',
            # tell our test script that it's running in shadow,
            # primarily so that it skips DNS resolution through tor proxy tests.
            f'{common.RUNNING_IN_SHADOW_ENV}=1',
            # tell "chutney verify" to listen on and connect back to the controller's ip address.
            f'{chutney.network_tests.verify.VerifyConfig._LISTEN_ADDRESS_ENV.varname()}={str(controller_ip)}',
            str(_SCRIPT_DIR.joinpath("test")), "-v"]),
        network_graph=network_graph,
    )
    #shadow_config.setdefault('experimental', scfg.Experimental())['strace_logging_mode'] ="standard"
    #shadow_config.setdefault('host_option_defaults', scfg.HostOptions())['pcap_enabled'] = True
    # Add the TEST_DOMAIN web server
    shadow_config['hosts'][common.TEST_DOMAIN] = scfg.Host(
        network_node_id=network_graph.default_node_id(),
        ip_addr=str(test_domain_ip),
        processes=[
            scfg.Process(
                path="python3",
                args="-m http.server 80",
                start_time=0,
                expected_final_state="running",
            )
        ],
    )

    # write out the shadow config file
    shadow_config_path = network.dir.joinpath("shadow.yaml")
    with shadow_config_path.open("w") as shadow_yaml:
        # We avoid the 'pyyaml' serializer because shadow parses as yaml
        # 1.2, and pyyaml generates output compliant with yaml 1.1, but not
        # always yaml 1.2.
        # <https://github.com/yaml/pyyaml/issues/860>
        #
        # yaml 1.2 is designed to be a strict superset of json, so we can
        # use the json encoder instead.
        json.dump(
            shadow_config,
            shadow_yaml,
            indent=4,
        )

    shadow_path = Path("shadow")
    shadow_exec.run_shadow_watching_process(
        shadow_bin=shadow_path,
        shadow_config_path=shadow_config_path,
        watch_host=controller_hostname,
        dstdir=network.dir,
    )

#    chutney.shadow.run_in_shadow(
#        network,
#        node_latency="1ms",
#        node_bandwidth="1 Gbit",
#        node_packet_loss=0.0,
#        controller_args=[str(_SCRIPT_DIR.joinpath("test")), "-v"],
#    ) 

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="integration-e2e-shadow",
        description="Runs integration-e2e inside a shadow simulation",
    )
    parser.set_defaults(func=_configure_and_run_shadow)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
